### ISSUE TITLE
Make app SEO friendly

### ISSUE THREAD

**Issue by snolflake** [snolflake/graphs-and-tracks#84]
![screenshot from 2017-01-16 15-33-36](https://cloud.githubusercontent.com/assets/1047033/21993292/3f70b1a6-dc01-11e6-870a-a736f205fc3f.png)

**Comment by bykbtzr** [comment]
Seems better now...

---------

![screenshot from 2017-01-28 13-45-08](https://cloud.githubusercontent.com/assets/1047033/22397769/16e08a96-e560-11e6-8851-e52945b993c6.png)
